# Generated by Django 2.2.5 on 2022-08-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220816_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('jpy', 'JPY'), ('usd', 'USD')], max_length=3),
        ),
    ]
