# Generated by Django 2.2.5 on 2022-09-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220817_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('jpy', 'JPY'), ('usd', 'USD')], default='jpy', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('jp', 'Japanese'), ('en', 'English')], default='jp', max_length=2),
        ),
    ]
