# Generated by Django 2.2.5 on 2022-08-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instant_nook',
            new_name='instant_book',
        ),
    ]
