# Generated by Django 2.2.5 on 2022-08-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220809_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bed',
            new_name='beds',
        ),
    ]
