# Generated by Django 2.2.5 on 2022-08-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220815_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedromms',
            new_name='bedrooms',
        ),
    ]
