# Generated by Django 2.2.5 on 2022-08-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220815_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='accurancy',
            new_name='accuracy',
        ),
    ]
